In [2]:
#import necessary library
import numpy as np
import pandas as pd

In [5]:
#import sklearn load dataset
from sklearn.datasets import load_iris
iris_dataset = load_iris()

In [7]:
#display the dataset type
type(iris_dataset)

sklearn.utils.Bunch

In [9]:
#View information using dataset built in method DESCR
print(iris_dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [11]:
#view features
print(iris_dataset.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [13]:
#view target
print(iris_dataset.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [14]:
#find number of observations  #150 observations #4 variables
print(iris_dataset.data.shape)

(150, 4)


In [15]:
#Assign features data to X axis
X_feature =iris_dataset.data

In [16]:
Y_target = iris_dataset.target

In [18]:
print(X_feature.shape)
print(Y_target.shape)

(150, 4)
(150,)


In [20]:
#First use KNN classifier method - import it from sklearn
from sklearn.neighbors import KNeighborsClassifier

In [23]:
#instantiate the knn estimator
knn = KNeighborsClassifier(n_neighbors=1)
print(knn)

KNeighborsClassifier(n_neighbors=1)


In [25]:
# fit data into KNN model (estimator)
knn.fit(X_feature, Y_target)

KNeighborsClassifier(n_neighbors=1)

In [26]:
#create object with new values for prediction
x_new = [3,5,4,1],[5,3,4,2]

In [28]:
knn.predict(x_new)

array([1, 1])

In [30]:
#use the Logistic regression estimator 
from sklearn.linear_model import LogisticRegression
logReg = LogisticRegression()

In [36]:
logReg.fit(X_feature, Y_target)

/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [38]:
#predict the outcome using Logistic regression estimator
logReg.predict(x_new)

array([0, 1])

In [42]:
#KMeans Clustering libraries
import numpy as np
from sklearn.cluster import KMeans
from sklearn.datasets import make_blobs

In [46]:
#define number of samples
n_samples = 300
#define random state value to initialize the center
random_state = 20
#define number of feature as 5
X,y = make_blobs(n_samples=n_samples,n_features=5,random_state=None)
predict_y = KMeans(n_clusters=3,random_state=random_state).fit_predict(X)
predict_y

array([1, 1, 0, 2, 1, 0, 0, 2, 2, 2, 0, 0, 0, 1, 2, 1, 1, 2, 0, 1, 0, 0,
       1, 1, 1, 1, 2, 2, 0, 2, 1, 0, 0, 2, 0, 1, 1, 2, 2, 0, 2, 1, 1, 1,
       1, 2, 1, 0, 1, 2, 2, 0, 0, 1, 1, 0, 2, 2, 0, 2, 0, 0, 1, 0, 1, 1,
       0, 2, 2, 0, 0, 1, 1, 2, 1, 1, 2, 2, 1, 1, 0, 1, 1, 0, 1, 0, 2, 1,
       1, 1, 2, 0, 1, 1, 2, 0, 2, 0, 1, 0, 0, 1, 2, 0, 2, 0, 2, 1, 2, 0,
       1, 1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 0, 2, 2, 2, 2, 0, 2, 1,
       0, 2, 0, 1, 1, 0, 1, 1, 0, 2, 1, 0, 2, 0, 0, 2, 1, 2, 0, 0, 0, 1,
       1, 2, 2, 1, 2, 2, 2, 1, 2, 1, 0, 2, 2, 1, 1, 2, 0, 1, 0, 2, 0, 0,
       0, 0, 0, 2, 0, 1, 2, 2, 1, 0, 1, 0, 2, 1, 2, 0, 2, 1, 0, 2, 0, 1,
       0, 0, 2, 1, 1, 2, 2, 2, 1, 2, 2, 2, 1, 1, 0, 2, 0, 1, 1, 1, 2, 2,
       2, 0, 0, 0, 2, 0, 0, 1, 1, 0, 2, 2, 2, 0, 0, 2, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 2, 1, 1, 2, 2, 1, 2, 1, 1, 0, 2, 0, 1, 2, 0, 0, 2,
       2, 0, 0, 0, 2, 2, 1, 0, 0, 0, 2, 1, 0, 0, 2, 0, 1, 0, 0, 0, 2, 2,
       2, 0, 2, 2, 1, 0, 2, 1, 2, 1, 0, 2, 2, 1], d

In [53]:
#import required library PCA
from sklearn.decomposition import PCA
#import the dataset
from sklearn.datasets import make_blobs

In [55]:
#define sample and random state
n_sample = 20
random_state = 20

In [56]:
#Generate the datset with 10 features (dimension)
X,y = make_blobs(n_samples=n_sample,n_features=10,random_state=None)

In [57]:
#view the shape of the dataset #20 observations #10 attributes
X.shape

(20, 10)

In [63]:
#define the PCA estimator with number of reduced components #How much variacne is explained with each component 
pca = PCA(n_components=3)
pca.fit(X)
print(pca.explained_variance_ratio_)

[0.56065181 0.41200832 0.00639619]


In [65]:
#print the first PCA component 
first_pca = pca.components_[0]
print(first_pca)

[ 0.39855355  0.19218695  0.26653074  0.19422064  0.42942348  0.2653167
 -0.23900035  0.28330753 -0.16819041 -0.52439406]


In [67]:
pca_reduced = pca.transform(X)

In [68]:
#view the reduced shape (Lower dimension) #Reduced dimensions from 10 to 3
pca_reduced.shape

(20, 3)

In [75]:
#Building a pipeline 

#import pipeline class
from sklearn.pipeline import Pipeline

#import linear estimator
from sklearn.linear_model import LinearRegression

#import PCA estimator for dimensionality reduction
from sklearn.decomposition import PCA

In [76]:
estimator =[('dim_reduction',PCA()),('linear_model',LinearRegression())]

In [77]:
pipeline_estimator = Pipeline(estimator)

In [78]:
pipeline_estimator

Pipeline(steps=[('dim_reduction', PCA()), ('linear_model', LinearRegression())])

In [79]:
pipeline_estimator.steps[0]

('dim_reduction', PCA())

In [80]:
pipeline_estimator.steps[1]

('linear_model', LinearRegression())

In [81]:
pipeline_estimator.steps

[('dim_reduction', PCA()), ('linear_model', LinearRegression())]